user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    #default_type  application/octet-stream;
    default_type  application/json;

#    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                      '$status $body_bytes_sent "$http_referer" '
#                      '"$http_user_agent" "$http_x_forwarded_for"';

    log_format  main  '"$time_iso8601" $client_real_ip "$country_header" '
                      '"$remote_user" $host "$request" '
                      '$status b_out=$body_bytes_sent b_in=$request_length '
                      'res_t="$upstream_response_time" req_t="$request_time" '
                      '"$http_user_agent" "$http_referer" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
